### PR TITLE
createBackgroundTransaction is being deprecated

### PR DESCRIPTION
**Pull request by MarkPareja**
createBackgroundTransaction is being deprecated, replaced by startBackgroundTransaction

### CODE REVIEW

**Comment by evantahler** [comment]
Do you need to include a version bump to the newrelic package this refreneces?

**Comment by MarkPareja** [comment]
yes, 2.2.0

**Comment by evantahler** [comment]
You should make that a `peerdependency` then in the package.json  https://docs.npmjs.com/files/package.json#peerdependencies

**Comment by MarkPareja** [comment]
added peer dep.

**Comment by evantahler** [comment]
Thanks!

**Comment by evantahler** [comment]
```
> npm publish
+ ah-newrelic-plugin@0.5.0
```

**Pull request merged**
